@startuml

Alumno --> Materia
Inscripcion o-- Materia
Inscripcion o-- Alumno

class Inscripcion {
- alumno: Alumno
- asignaturas: [Materia]
esExitosa() -> Bool
}

class Materia {
- correlativas: [Materia]
puedeCursar() -> Bool
}

class Alumno {
- aprobadas: [Materia]
aprobar()
}

@enduml